FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/reservation/cmd/main
RUN go build -o /app/reservation/reservation .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/reservation/reservation .

EXPOSE 8082
CMD ["./reservation"]
