services:
  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - app-network

  cubicle:
    build:
      context: .
      dockerfile: Dockerfile.cubicle
    container_name: cubicle
    depends_on:
      - consul
      - metadata
      - reservation
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - "8083:8083"
    networks:
      - app-network

  metadata:
    build:
      context: .
      dockerfile: Dockerfile.metadata
    container_name: metadata
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - "8081:8081"
    networks:
      - app-network

  reservation:
    build:
      context: .
      dockerfile: Dockerfile.reservation
    container_name: reservation
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
